on: push
jobs:
  build-debian:
    runs-on: ubuntu-latest
    container:
      image: debian
    steps:
      - run: echo 'Hola desde Debian'
      - run: hostnamectl
      - uses: actions/checkout@v3
