on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container:
      image: debian
    steps:
      - run: sudo apt update
      - run: sudo apt upgrade
      - run: echo 'Hola desde Debian'
      - uses: actions/checkout@v4
      - run: node app.js
