on: push
jobs:
  build-debian:
    runs-on: ubuntu-latest
    container:
      image: debian
    steps:
      - run: echo 'Hola desde Debian'
      - run: apt-get update
      - run: apt-get upgrade
      - run: cat /etc/os-release
      - uses: actions/checkout@v3
